export const enum ChessMove {
  NOT_APPLICABLE,
  ILLEGAL_MOVE,
  WRONG_PLAYER,
  REGULAR_MOVE,
  CAPTURE_MOVE,
  PROMOTION_MOVE,
  EN_PASSANT_MOVE,
  LONG_CASTLE,
  SHORT_CASTLE,
  CHECK_MOVE,
  CHECKMATE_MOVE,
}

export const enum ChessStatus {
  NOT_APPLICABLE,
  REGULAR,
  CHECK_WHITE,
  CHECK_BLACK,
  CHECKMATE_WHITE,
  CHECKMATE_BLACK,
  STALEMATE_WHITE,
  STALEMATE_BLACK,
  DRAW,
}
